### ISSUE TITLE
OCS: Impact Research: Define participants

### ISSUE THREAD

**Issue by LAStorm** [hackforla/open-community-survey#106]
### Overview
Organize the contact details for all research participants so that we are ready to do outreach when the training instructions have been created.

### Action Items
- [x] Review impact research plan
- [x] Create spreadsheet of people to interview listing name, affiliation, title (if applicable), contact information
- [x] Add all the people from our various sources as defined by the research plan
- [x] Add link to the research wiki page
- [x] Remove dependency on #109 

### Resources/Instructions
- Impact Research wiki page: https://github.com/hackforla/open-community-survey/wiki/User-Research
- [EmpowerLA.org website redesign wiki](https://github.com/hackforla/community-survey-empowerLA-website/wiki/Process)
- Spreadsheet of Potential Interviewees: https://docs.google.com/spreadsheets/d/1qQtvTz_EcOdYQdZe3eXniQ0hVMkCWSBxRN1kBcmQOcg/edit?usp=sharing

From the research plan:
Participants will include stakeholders from these groups: 

1. EmpowerLA (3-4 people including the Director of Innovation, the General Manager, and 2-4 staff members) 
- SEIE survey (Gibson N. and Raquel)
- EmpowerLA website (Julien and various other people) 
2. Neighborhood Councils (3-4 people)
3. Hack for LA volunteers (3-4 people) who worked on Empower LA website redesign workshop.  
4. Hack for LA volunteers (3-4 people) who worked on the SEIE survey
5. Vendor who donated services (1-2) people from the company that conducted the website redesign workshops, Super by Design. 

If the currently planned interviews yield suggestions for other people to interview, we may add interviewees and interview questions. We expect to interview at least 9-16 participants for this project. 

### Related issues
- #20 
- [ ] #108
- [ ] #96 
- [ ] #103
- [ ] #109

**Comment by LAStorm** [comment]
Created spreadsheet. Many of the names are TBD because we need referrals to specific people. I know I have seen a spreadsheet of Hack for LA volunteers who participated in the website redesign workshops, but now I cannot find it.

**Comment by kalyaniraman** [comment]
@ExperimentsInHonesty Can you please point Snow to the folder/file that had information(specifically recordings & rosters) on Website Redesign Workshop

**Comment by LAStorm** [comment]
I found the information I was looking for! It was linked from the [EmpowerLA.org website redesign wiki](https://github.com/hackforla/community-survey-empowerLA-website/wiki/Process)

**Comment by LAStorm** [comment]
I found the information I was looking for. I updated the spreadsheet of potential interviewees at: https://docs.google.com/spreadsheets/d/1qQtvTz_EcOdYQdZe3eXniQ0hVMkCWSBxRN1kBcmQOcg/edit?usp=sharing

Note: Our listed goal is to interview up to 4 people per category. In some categories, we have more potential interviewees than that. I listed them all on the spreadsheet for outreach purposes. Most likely not everyone will be available. It also might be all right to have more than 4 interviews in a few categories.

Outstanding Issues:

- I was able to find e-mail addresses for the Hack for LA volunteers who conducted the website redesign workshops. I do not have e-mail addresses for anyone else. We will need to find a way to get them or some other way to contact people for scheduling and interviews.
- There were two participants who needed Spanish translation and one who needed closed captioning because he is Deaf. We may need to make similar accommodations for the interviews if we are able to interview those participants.
- I am not sure how to find the current/recent Hack for LA volunteers who worked on the SEIE survey.

**Comment by LAStorm** [comment]
@ExperimentsInHonesty I could use help with the following:

- Developing a plan for how to contact people who work for the Dept of Neighborhood Empowerment or are members of neighborhood councils.
- Determining how or whether to prioritize people to contact.
- Finding current/recent Hack for LA volunteers who worked on the SEIE survey. (I do know Henry Kaplan - do I ask him?)

None of this is super urgent because we are not ready to begin interviewing yet. They are blockers to completing this part of the plan though.

**Comment by kalyaniraman** [comment]
- SEIE Survey team members - Henry Kaplan, Sarah Nooravi ,Sathwik Kesappragada, Randy Rios, Solee Shin, Bonnie Wolfe
- From city - Julien Antelin , Gibson Nyambura, 
- HFLA Volunteers - Grace Jones - sljmovingfoward@gmail.com, Abe Khaleghi, Justin Lee
- [Roster in Data Science Team](https://docs.google.com/spreadsheets/d/1xpSwi0shccL01_qQ8qIx-W2tzzfkcaTIS3UyQtmKFeY/edit#gid=0)
- Added Snow to the DS to be able to access the Roster

**Comment by LAStorm** [comment]
Made progress with filling in the e-mail addresses. Missing a few for Dept of Neighborhood Empowerment employees (which we may be able to figure out from the pattern of the others) and for Hack for LA volunteers who worked on the SEIE survey.

**Comment by LAStorm** [comment]
Thanks to @ExperimentsInHonesty, we were able to find e-mail addresses for all but 2 potential interviewees.

I just added the link to the spreadsheet of potential interviewees to the wiki.

**Comment by LAStorm** [comment]
@ExperimentsInHonesty Do you want to try to find the remaining 2 e-mail addresses, or not worry about it?

**Comment by ExperimentsInHonesty** [comment]
Bonnie will talk to Raquel next week 15th-19th
