### ISSUE TITLE
Create Background Image for OCS Zoom Meetings

### ISSUE THREAD

**Issue by kalyaniraman** [hackforla/open-community-survey#107]
### Overview
We need to have a background image that can be used in Zoom meetings and also be available in the shared folder to anyone to download prior to meetings with stakeholders.

### Action Items

- [x] Create a background image to be used in Zoom Meetings .
  - [x] Need to contain HackForLA Logo 
  - [x] Need to contain OCS Logo
- [x] Add image to communication guide with a link to download from google drive folder 
- [x] Add this to the UXR page in wiki to be used in interviews (see TDM Calculator project for reference). 

### Resources/Instructions

- [TDM Calculator UXR Onboarding - Second Round [TEMPLATE]](https://docs.google.com/presentation/d/1VUTxh5eR0PHUAhaU8ZgNlsnrj_qmaBXcv9IUmfR0aTs/edit?usp=sharing)
- [OCS Communication Guide](https://docs.google.com/presentation/d/1V_JVpqLadtYUQDdDfVUmYmgt-nCfvz_tNTFkWmbNeG0/edit?usp=sharing)
- [OCS Wiki](https://github.com/hackforla/open-community-survey/wiki/User-Research)
- [Link to Potential Background Image](https://unsplash.com/photos/ukvgqriuOgo)
- [HackForLALogo](https://github.com/hackforla/product-management/projects/2#card-51755660)
- [OCS Zoom Background Logo](https://drive.google.com/drive/u/0/folders/1GA-NT0JFQN_QwKLxFFb-kiymEpYSmKKU)

**Comment by kalyaniraman** [comment]
@mkleibman 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by mkleibman** [comment]
Per meeting 5/9:

Create final Zoom background images for consideration. All options will be on top, with logos together based on feedback. Make sure to

- [ ] Fix pixel drop issue on Figma export, make sure image is clean for final considerations.

Create and add the following images to Drive:
- [ ] White sky, upper left, full rectangle 
- [ ] White sky, upper left, corner flag 
- [ ] White sky, upper left, no rectangle
- [ ] Blue sky, upper left, full rectangle
- [ ] Blue sky, upper left, corner flag
- [ ] Blue sky, upper left no rectangle

**Comment by kalyaniraman** [comment]
We are good with White No box until we see the one with full blue bar. Then we will see all three of them with the blue

**Comment by kalyaniraman** [comment]
@mkleibman I see only the following in the OCS drive. Can you please upload the other images with blue again? Thanks
![image](https://user-images.githubusercontent.com/66500215/178090185-6b2629f7-1d3e-404a-86a8-0e019a6fc1fb.png)

**Comment by kalyaniraman** [comment]
@mkleibman 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@mkleibman is this still outstanding or has it been completed?  If still outstanding, do you want to summarize what still needs to be done and put it in the prioritized backlog for later?

**Comment by joshfishman** [comment]
Added Zoom Backgrounds to Wiki
https://github.com/hackforla/open-community-survey/wiki/Resources
