### ISSUE TITLE
Create visual version of all User Journeys

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/open-community-survey#110]
### Overview
We need to turn the written user journeys  into visual representations so that it is easy to audit the wireframes

### Action Items
- [x] Create a fig jam file and create a section for each User Journey 
- [x] Create the text that will go in each one below under _Content for each issue_
- [x] Create issues for each Journey
  - [x] #116
  - [x] #117
  - [x] #118
  - [x] #119
- [x] Add content to each issue
- [x] Customize the resources with a link to fig jam section for that Journey
- [x] Update Dependency on #73 to have the issues of visual journeys

### Resources/Instructions
- [OCS: Website Audience and Personas](https://docs.google.com/document/d/1qTqxgMRi7y7Qqt1LvSDoPXGQOYGzH49_KM4txghBMkQ/edit#)
- [OCS: Figma account](https://www.figma.com/files/project/29579795/First-project?fuid=775836858007206739) - location to create new figjam file
- [OCS: Figma, Figjam: User Journeys](https://www.figma.com/file/IDBkJinlOUFtaqsPHDCGvO/User-Journeys?node-id=0%3A1)

#### Content for each issue
```
### Overview
We need to turn the written user journey for [insert section name]  into visual representations so that it is easy to audit the wireframes

### Action Items
- [ ] Go to the [insert section name] in figjam
- [ ] Read the User Journey from the Audience and Personas document
- [ ] Create a visual version

### Resources/Instructions
- [OCS: Website Audience and Personas](https://docs.google.com/document/d/1qTqxgMRi7y7Qqt1LvSDoPXGQOYGzH49_KM4txghBMkQ/edit#)
- [OCS: Figma, current designs](https://www.figma.com/file/04T31AqsprIIkuBN4OfwOo/Open-Community-Survey-Designs?node-id=108%3A289)

```

**Comment by ambersu123** [comment]
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
