### ISSUE TITLE
Conduct UX/UI impact research draft/pilot

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/open-community-survey#3]
We need to conduct impact research on Empowerla.org website redesign community workshop initiative so that we can use the information for website content

- [x] Create list of questions to elicit success stories from stakeholders
- [x] Share questions with team (esp Bonnie)
- [x] Send questions to stakeholder before meeting on Friday
- [ ] Convert questionnaire into template (org asset)
   - [ ] Connect researcher to senior UI/UX researcher - Roseline
   - [ ] Refine questionnaire
- [ ] Conduct impact research on other stakeholders

### Resources 
[Impact Research Questions Draft](https://docs.google.com/document/d/1c29WhIUzVYm1A8Zvn6CgnEBM3d9Ua0Eh3gE9jvk_SEc/edit)

**Comment by phoebeng** [comment]
This is a sample of the ASK to the stakeholders. Feel free to edit and revise! 

Hi there, 

Thank you for your participation in the [PROJECT NAME]! 

This was one of the first projects to spark a larger initiative: The Open Community Survey Project. At Hack for LA, our goal is to continue building the Open Community Survey Project with more initiatives that have a common mission of amplifying citizens’ voices and influence more citizen engagement. 

We are looking to get user/stakeholder perspectives to measure the impact of the project you were involved with. Would you be able to schedule a time in the next few weeks for a [TIME FRAME] interview about your experience and perspective with this project? 

Thank you and hope to hear from you soon! 

Best, 
[NAME/ORG]

**Comment by ebele-oputa** [comment]
@phoebeng please could you create a list of the interview questions separately and include a link to the issue? Thanks!

**Comment by ExperimentsInHonesty** [comment]
@phoebeng no need to do a doc with the questions @csdorsey has done that in the research plan.  I will assign you from this issue.  Thank you so much!  🥰

**Comment by ExperimentsInHonesty** [comment]
We will take the info from this issue and add it to a form research plan.
