### ISSUE TITLE
Get Videos on EmpowerLA Website Redesign Project

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/open-community-survey#32]
### Overview
We need to obtain additional recordings on the EmpowerLA website redesign project so that we can use for design ideas, etc

### Action Items
- [x] Reach out to Julien 

### Resources/Instructions
[EmpowerLA website redesign](https://github.com/hackforla/community-survey-empowerLA-website/wiki/Process)

**Comment by ExperimentsInHonesty** [comment]
Here are the videos: 

For the main room:
https://us02web.zoom.us/rec/play/TSvRf7btTYEldKOrpmz9ue7G9cISddPHZ0AW3ecIQFrnFoWimm-xtJieSkdXq7hbyVlX1vISM9mBBGbx.Lpz0-dXIB1Y1NlI5
https://us02web.zoom.us/rec/play/VFk26k_bV4cToX_oy-EEhBi51foXzkpGEgc8b0nsj26DxxQ-vldTsFgjHzPLHNa3bZzY6FTucP9GNZfi.M65hctU8A7bUpBIE

For the breakout room, all the video are in the folder:
https://drive.google.com/drive/folders/1MQnUWv-AzeX0-XFAer8lQrxXe04YCkSw

**Comment by ebele-oputa** [comment]
@ebele-oputa download and add to the Drive

**Comment by ExperimentsInHonesty** [comment]
I reached out to Eric from Westlake to get any recordings from him

**Comment by ebele-oputa** [comment]
@ExperimentsInHonesty passcode required  for "main room" videos and access needed for "breakout room" video

**Comment by ebele-oputa** [comment]
@ExperimentsInHonesty send email reminding Julien about password

**Comment by ebele-oputa** [comment]
@ExperimentsInHonesty to talk to Julien on Friday

**Comment by ebele-oputa** [comment]
@ebele move videos and link to this wiki - https://github.com/hackforla/community-survey-empowerLA-website/wiki/Process

**Comment by ebele-oputa** [comment]
> @Ebele move videos and link to this wiki - https://github.com/hackforla/community-survey-empowerLA-website/wiki/Process

Done!
