### ISSUE TITLE
Recruit New UI/UX Researcher

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/open-community-survey#37]
### Overview
We need to recruit a UI/UX researcher to assist the team in implementing project tasks.

### Action Items
- [x] Create job posting on UI/UX job board
- [x] Speak to CoP lead about post
- [x] Schedule meeting with Chianta to handover tasks
- [x] Onboard new team member

**Comment by ExperimentsInHonesty** [comment]
- [x] Move posting from filled to ux researcher column and edit as appropriate
- [ ] Post in UI/IX channel
- [ ] Speak to CoP lead about post
- [ ] If we don't get someone organically, go present to UI/UX community of practice
- [ ] If we don't get someone from CoP, show up at onboarding night
- [ ] Onboard new team member

**Comment by kalyaniraman** [comment]
- [x] Move posting from filled to ux researcher column and edit as appropriate
- [x] Post in UI/IX channel 
- [ ] Speak to CoP lead about post
- [ ] If we don't get someone organically, go present to UI/UX community of practice
- [ ] If we don't get someone from CoP, show up at onboarding night
- [ ] Onboard new team member

**Comment by kalyaniraman** [comment]
- [x] Move posting from filled to ux researcher column and edit as appropriate
- [x] Post in UI/IX channel 
- [x] Speak to CoP lead about post - Slacked Kevin
- [ ] If we don't get someone organically, go present to UI/UX community of practice
- [ ] If we don't get someone from CoP, show up at onboarding night
- [x] Onboard new team member
