### ISSUE TITLE
Label project: Create new, edit old, apply

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/open-community-survey#38]
### Overview
We need to have a label system that helps to navigate the project board , prioritize issues and standardize with the rest of the HfLA team structures.

### Action Items
- [x] fix existing labels by category
   - [x] role related labels to be prefixed with  "role: "
   - [x] internal feature labels to be prefixed with "feature: "
   - [x] external feature labels to be prefixed with "p-feature: "
- [x] add labels that do not yet exist
   - [x] role (add any that are missing)
     - [x] role: missing
   - [x] feature (add any that are missing)
      - [x] feature: missing
  - [x] size (add any that are missing)
      - [x] size: missing
   - [x] size
      - [x] size: 1pt
      - [x] size: 2pt
      - [x] size: 3pt
      - [x] size: 5pt
      - [x] size: 8pt
      - [x] size: 13+pt
- [x] replace all missing labels with appropriate labels
- [x] meet with Bonnie for final review

**Comment by ebele-oputa** [comment]
I have added labels to all closed issues.
@jonarcisse and I will meet next week to complete the remaining tasks

**Comment by ebele-oputa** [comment]
Questions to be answered by Bonnie:
1) The use of the prioritised backlog and its position on the board
2) Clarification on the labels
