### ISSUE TITLE
Figma Reorganization

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/open-community-survey#39]
### Overview
We need to reorganize our Figma pages so that all documentation is in one place and we have ordered list of design pages

### Action Items
- [x] Find Figma account with multiple pages
- [x] Transfer all Figma content to new account

### Resources/Instructions
[New Figma Account](https://www.figma.com/file/04T31AqsprIIkuBN4OfwOo/Open-Community-Survey-Designs?node-id=0%3A1)

**Comment by ebele-oputa** [comment]
@kvnw2020 @AdesinaBernard please transfer all designs to this Figma account. Thanks 

https://www.figma.com/file/04T31AqsprIIkuBN4OfwOo/Open-Community-Survey-Designs?node-id=0%3A1

**Comment by kvnw2020** [comment]
All files transferred.

**Comment by ebele-oputa** [comment]
@ebele-oputa replace with new sigma link
