### ISSUE TITLE
Conduct comparative analysis of NC websites

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/open-community-survey#4]
### Overview
We need to conduct a comparative analysis of the 99 NC websites so as to identify common and missing features for web development

### Action Items

- [x] Create a spreadsheet of NC websites
- [x] UX/UI CA Workshop
- [x] Technical Workshop 
   - [x] Reach out to Greg Pawin and organize a Comparative Analysis Workshop for the Dev Community of Practice 
   - [x] Coordinate with Dean to have him talk at the workshop
   - [x] Conduct workshop
- [x] Complete the comparative analysis

### Resources 
[Comparative Analysis Sheet](https://docs.google.com/spreadsheets/d/1V5cOCwABGNsvp715EL-SIRklcknEJB-hj4Mtjl8zMpw/edit#gid=1687401058)
[List of 99 NC Websites](https://docs.google.com/spreadsheets/d/1WWaZxaShswlTMWvDjD9LGw3AUAE_yU2e1018Yh6guVk/edit#gid=236874988)

**Comment by ExperimentsInHonesty** [comment]
I met with data science team and asked them to use builtwith.com or analyze the technology behind each site.  I will meet with the Ops team to talk about if we can find last updated date in an automated way so that we know when you update our data.

**Comment by ExperimentsInHonesty** [comment]
@csdorsey says she will do 10 per week

**Comment by ebele-oputa** [comment]
@csdorsey Please train Kevin and @AdesinaBernard to do some comparative analysis

**Comment by ebele-oputa** [comment]
@ExperimentsInHonesty do not forget to get volunteers at onboarding session to work on this as well!!!!!!!

**Comment by csdorsey** [comment]
The website comparison portion of the comparative analysis has been completed.

**Comment by ebele-oputa** [comment]
@ebele-oputa Link this to the wiki. Make sure everyone can view but not edit

**Comment by ebele-oputa** [comment]
@csdorsey please create another issue for comparative analysis page content
