### ISSUE TITLE
Usability Testing of OCS Comparative Analysis

### ISSUE THREAD

**Issue by kvnw2020** [hackforla/open-community-survey#41]
### Overview
We need to perform a usability testing of the Comparative Analysis to streamline OCS Research Team's effort to identify pain point along the analysis user journey.

### Action Items
- [x] Create a research plan.
- [x] Review plan with Research Team
- [x] Gather testing requirements
- [x] Test Run
- [x] Recruit participants
- [x] Execute usability test
- [x] Synthesize collected data
- [x] Produce deliverables for OCS Team

### Resources/Instructions
[Usability Test Reseach Plan Draft](https://docs.google.com/document/d/1YXXibO510eA4Mff4ZGSF-duibGGZruAA/edit?usp=sharing&ouid=100778618739654876042&rtpof=true&sd=true)
[Copy of Comparative Analysis for Usability Testing](https://docs.google.com/spreadsheets/d/114eFpeKQfyXaG4iFZlycdvt5UtxkNiTR0PDvn0emzJg/edit#gid=259269486)
[Usability Testing Framework](https://docs.google.com/spreadsheets/d/10hX5Syut9tNbwfva3K-ow8dOzzQ07SPDT8Nhz1Ds1-s/edit#gid=3)
[Usability Test Recording](https://drive.google.com/drive/u/0/folders/1sIIC1q2IS1Ym0m4YlA3rmhGJTY030V4r)
[Findings and Insight Rough Draft](https://docs.google.com/document/d/1Pcw3sYNphIcos15uSVh7Dy76zpJDRYLU9fcXfPGfqUs/edit?usp=sharing)
[Usabiltiy Test Synthesis](https://www.notion.so/ac971f6a931f4758921286d1982c900a?v=5c26aa6dd366447ab2f0e49e618cf3d8)
[Miro board](https://miro.com/welcomeonboard/djZxTlRzTVVteXlnMDk1eUtpV3loZDB6eHZ0WFQ5WERuVExYWnoxTjllV3ZCQzFpV2w3cWtZR3I0Z253UzNtMHwzMDc0NDU3MzUwNDIxNTAzNTE3?invite_link_id=549381002247)
Usability Test Analysis https://docs.google.com/document/d/1eX9P_lQj6Uh5aZmK8p_WsC65t9ReqKPwWIfUXA15Ypc/edit

**Comment by kvnw2020** [comment]
Found a template for moderated usability testing.
[Usability Test Analysis](https://docs.google.com/spreadsheets/d/10hX5Syut9tNbwfva3K-ow8dOzzQ07SPDT8Nhz1Ds1-s/edit#gid=2)

**Comment by kvnw2020** [comment]
Need a consensus on 5 NC websites for testing.

**Comment by kvnw2020** [comment]
Recruited 3 test participants thus far. Performed 1 usability test. Scheduled 2 more this week.

**Comment by ebele-oputa** [comment]
@jonarcisse help with recruitment of 2 participants for the survey

**Comment by kvnw2020** [comment]
Discovered some findings and insight after usability testing. Placed in [Google Doc](https://docs.google.com/document/d/1Pcw3sYNphIcos15uSVh7Dy76zpJDRYLU9fcXfPGfqUs/edit?usp=sharing) and [data analysis](https://www.notion.so/ac971f6a931f4758921286d1982c900a?v=5c26aa6dd366447ab2f0e49e618cf3d8)

**Comment by ebele-oputa** [comment]
@kvnw2020 to migrate data analysis from Notion to Google Sheet. Also, please schedule a meeting UX team to analyse findings

**Comment by LAStorm** [comment]
We had an additional team meeting on 10/28 to discuss next steps. Decision: "Implement the recommendations and test it again." Especially on Data Science Community of Practice and on Bonnie.
