### ISSUE TITLE
Update Project Profile: Review and Update

### ISSUE THREAD

**Issue by jonarcisse** [hackforla/open-community-survey#42]
### Overview
We need to update our project card on the HFLA website to include new team members and remove inactive members so that people looking to join or understand our project will know who the current contacts for the team are

### Action items
- [x]  Identify who is currently on the hack for LA website for the project
- [x] Determine people needing to be removed
- [x] Determine people needing to be added
- [x] Collect information for team members to be added (should be in the team roster)
   -  Name
   - Role
   -  Slack ID
   -  GithHub handle
- [x] update the hackforla.org website team by opening an issue (see below)
- [x] Add the issue link to the Current Open Issue section

### Resources
HackforLA.org, Open Community Survey page: https://www.hackforla.org/projects/open-community-survey
[OCS Roster](https://docs.google.com/spreadsheets/d/1b97Np96EimkxicW83pwnYkn7uDd7fCD5H_6F21nOkg4/edit?usp=sharing)
[Open issue on hackforla.org website project board to update info for OCS](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)

### Closed issue (prior changes)
2021-10-11 [Issue on the website team's board](https://github.com/hackforla/website/issues/2364#issue-1023261996)

### Current Open Issue 
- 2022-01-22 https://github.com/hackforla/website/issues/2711

**Comment by ebele-oputa** [comment]
@jonarcisse have you created a new issue on the website team's board? If you have, then you need to link that issue to this one. If not, please create one

**Comment by ExperimentsInHonesty** [comment]
@ebele-oputa @jonarcisse I cleaned up the issue and put it in the prioritized backlog

**Comment by ExperimentsInHonesty** [comment]
Name
GitHub hand
Role
SLACK ID

**Comment by kalyaniraman** [comment]
#### Team Members to be Removed

    Name : Ebele
    GitHub hand : ebele-oputa
    Role : Product Manager
    SLACK ID : 

    Name : Chianta
    GitHub hand : csdorsey
    Role : UX Researcher
    SLACK ID : 

    Name : Sonu 
    GitHub hand : sonu-k
    Role : Data Analyst 
    SLACK ID : 

    Name : Amy Wilkins
    GitHub hand : amy-c-w
    Role : UX Researcher 
    SLACK ID : 

    Name : Jasmine Kim
    GitHub hand : jaskim20
    Role : UX Researcher 
    SLACK ID : 

    Name : Xintong(Shika) Zhou
    GitHub hand : ShikaZzz
    Role : Data Scientist 
    SLACK ID : 

    Name : JoAnne Narcisse
    GitHub hand : jonarcisse
    Role : Product Manager 
    SLACK ID :

**Comment by kalyaniraman** [comment]
Team Member to be Added

Name Kalyani Raman
GitHub hand kalyaniraman
Role Product Manager
SLACK ID U02QW65RU1M

**Comment by kalyaniraman** [comment]
Team Member to be Added

Name Kalyani Raman
GitHub hand kalyaniraman
Role Product Manager
SLACK ID U02QW65RU1M

Name Mary Kate Leibman
GitHub hand mkleibman
Role Researcher
SLACK ID U031V93CYB0

**Comment by kalyaniraman** [comment]
Here is the latest list of team members to be removed and added

**Team Members to be Removed**

Name : Ebele
GitHub hand : ebele-oputa
Role : Product Manager
SLACK ID : U01GJC7VC6L

Name : Chianta
GitHub hand : csdorsey
Role : UX Researcher
SLACK ID : U022B5EJFME

Name : Sonu 
GitHub hand : sonu-k
Role : Data Analyst 
SLACK ID : U027JBTAGSX

Name : Amy Wilkins
GitHub hand : amy-c-w
Role : UX Researcher 
SLACK ID : U0231JD5BC2

Name : Jasmine Kim
GitHub hand : jaskim20
Role : UX Researcher 
SLACK ID : U02AYE78X1Q

Name : Xintong(Shika) Zhou
GitHub hand : ShikaZzz
Role : Data Scientist 
SLACK ID : U029BAPRTA8

Name : JoAnne Narcisse
GitHub hand : jonarcisse
Role : Product Manager 
SLACK ID : U02AHBLDJ15

Name : Kevin Wang
GitHub hand : kvnw2020
Role : Designer
SLACK ID : U01GZHT5CM8

Name : Bernard
GitHub hand : AdesinaBernard
Role : Designer 
SLACK ID : U01FAP6GL23

**Team Members to be Added**

Name Kalyani Raman
GitHub hand kalyaniraman
Role Product Manager
SLACK ID U02QW65RU1M

Name Mary Kate Leibman
GitHub hand mkleibman
Role Researcher
SLACK ID U031V93CYB0

**Comment by kalyaniraman** [comment]
It got added to the website prioritized backlog for updating overview page on 3/21/2022.

**Comment by ExperimentsInHonesty** [comment]
It looks like they have not merged yet.  I have posted to them on Slack asking them to merge

**Comment by kalyaniraman** [comment]
@SAUMILDHANKAR moved the corresponding issue #2711 to QA

**Comment by kalyaniraman** [comment]
We reviewed the Open Community Survey website and all looks good.
