### ISSUE TITLE
Document Open Community Survey team meeting times and who Must/Should/Can attend

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/open-community-survey#45]
### Overview 
The Civic Tech Jobs team needs accurate meeting time information from the Open Community Survey team to help match your project with available volunteers.

### Action Items
- [x] provide details about each meeting in a comment by using a copy of the check boxes below
- [x] post a link to this issue on https://github.com/hackforla/CivicTechJobs/issues/35 in a comment letting the civic tech jobs team know you are done.
```
  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
```
### Resources
- URL of the project's homepage on the HfLA website:  https://www.hackforla.org/projects/open-community-survey
- Times that VRMS shows for your meetings: 
Mon 12:00 pm, 1 hour, Team Meeting

**Comment by jonarcisse** [comment]
- [x] day Monday
   - [x] start_time 12:00 
      - [ ] AM
      - [x] PM
   - [x] duration_in_min 60 min
   - [x] name_of_meeting Project meeting
   - [x] who_must_attend
      - [x] pm
      - [ ] all_leads
      - [x] design_lead
      - [x] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [x] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by jonarcisse** [comment]
Hi @ebele-oputa do you mind reviewing to make sure I have included the correct attendees?

**Comment by ebele-oputa** [comment]
> Hi @ebele-oputa do you mind reviewing to make sure I have included the correct attendees?

Done! @jonarcisse
