### ISSUE TITLE
Create issues for each milestone

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/open-community-survey#64]
### Overview
We need to go through our milestones with the aim of creating issues for each milestone so that we have a list of items for each role in our prioritised backlog, and are aware of our recruitment needs.

### Action Items
- [ ] Review milestones
- [ ] Create issues

### Resources/Instructions
[Milestones repo](https://github.com/hackforla/open-community-survey/milestones?direction=asc&sort=title&state=open)

**Comment by kalyaniraman** [comment]
We created issues to check each milestone.  [See issue tab](https://github.com/hackforla/open-community-survey/issues?q=is%3Aissue+is%3Aopen+milestone+milestone%3A%2204.+Project+Setup%22)
