### ISSUE TITLE
Update figma links

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/open-community-survey#71]
### Overview
We need to update the figma links so that everyone is working on the same file

### Action Items
- [x] Update Figma links

### Resources/Instructions
[Card with links to be updated](https://github.com/hackforla/open-community-survey/projects/1#card-66515054)
[New account file](https://www.figma.com/files/team/966536106289494893/Open-Community-Survey?fuid=966522772787660582)

**Comment by ExperimentsInHonesty** [comment]
This has been completed.  
- [new figma](https://www.figma.com/file/04T31AqsprIIkuBN4OfwOo/Open-Community-Survey-Designs?node-id=108%3A289)
- [Figma Team workspace ](https://www.figma.com/files/team/966536106289494893/Open-Community-Survey?fuid=775836858007206739)
